name: Java CI

on:
  push:
    paths:
      - mod.hjson

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up PATH
        run: |
          echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build mod jar
        run: |
          sed -i 's/\r//' ./gradlew
          chmod +x ./gradlew
          ./gradlew deploy -Pcommit=$(git rev-parse --short "$GITHUB_SHA")

      - name: Upload built jar file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: build/libs/${{ github.event.repository.name }}.jar

      - name: Delete all releases and tags
        run: |
          gh release list --limit 100 | awk '{print $1}' | xargs -I {} gh release delete {} -y
          git tag -l | xargs -n 1 git push --delete origin
          git tag -l | xargs -n 1 git tag -d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new tag
        run: |
          NEW_TAG=$(date +'%m-%d-%H-%M')
          git tag $NEW_TAG
          git push origin $NEW_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new release
        run: |
          NEW_TAG=$(date +'%m-%d-%H-%M')
          gh release create $NEW_TAG build/libs/${{ github.event.repository.name }}.jar --title "Latest release" --latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


