name: Replace with Files from Another Repo

on:
  push:
    branches:
      - main

jobs:
  replace_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v3

      - name: Remove all files in the current repository
        run: |
          rm -rf ./*
      
      - name: Checkout the files from the other repository
        uses: actions/checkout@v3
        with:
          repository: Noraxx1/implosion-java
          ref: master
          path: implosion-java

      - name: Copy files to the root directory
        run: |
          cp -r implosion-java/* ./
          rm -rf implosion-java

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Replace with files from Noraxx1/implosion-java"
          git push origin main
